import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import warnings
warnings.filterwarnings("ignore")
cars = pd.read_csv('datasets/cars.csv')
print('Dataset Information:')
print(cars.info())
print('\nSample Data:')
print(cars.head())
print('\nSummary Statistics:')
print(cars.describe(include='all'))
cars.columns = cars.columns.str.strip().str.replace(' ', '_').str.lower()
cars['price'].fillna(cars['price'].median(), inplace=True)
cars['size'].fillna(cars['size'].mode()[0], inplace=True)
cars['cars_sold'].fillna(cars['cars_sold'].median(), inplace=True)
cars['brand'] = cars['brand'].astype('category')
cars['type'] = cars['type'].astype('category')
plt.figure(figsize=(12, 8))
correlation_matrix = cars[['price', 'size', 'cars_sold']].corr()
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.2f', linewidths=0.5)
plt.title('Correlation Heatmap of Car Features')
plt.show()
plt.figure(figsize=(12, 8))
sns.pairplot(cars[['price', 'size', 'cars_sold']])
plt.suptitle('Pair Plot of Car Features', y=1.02)
plt.show()
plt.figure(figsize=(12, 6))
sns.histplot(cars['size'], bins=30, kde=True)
plt.xlabel('Size')
plt.ylabel('Frequency')
plt.title('Distribution of Car Sizes')
plt.show()
plt.figure(figsize=(14, 7))
sns.boxplot(x='brand', y='price', data=cars)
plt.xticks(rotation=90)
plt.xlabel('Brand')
plt.ylabel('Price')
plt.title('Price Distribution Across Car Brands')
plt.show()
plt.figure(figsize=(14, 7))
brand_sales = cars.groupby('brand')['cars_sold'].sum().sort_values(ascending=False)
sns.barplot(x=brand_sales.index, y=brand_sales.values)
plt.xticks(rotation=90)
plt.xlabel('Brand')
plt.ylabel('Total Cars Sold')
plt.title('Total Cars Sold by Brand')
plt.show()
plt.figure(figsize=(14, 7))
sns.boxplot(x='type', y='price', data=cars)
plt.xlabel('Car Type')
plt.ylabel('Price')
plt.title('Price Distribution Across Car Types')
plt.show()
plt.figure(figsize=(14, 7))
avg_price_by_brand = cars.groupby('brand')['price'].mean().sort_values(ascending=False)
sns.barplot(x=avg_price_by_brand.index, y=avg_price_by_brand.values)
plt.xticks(rotation=90)
plt.xlabel('Brand')
plt.ylabel('Average Price')
plt.title('Average Car Price by Brand')
plt.show()
plt.figure(figsize=(12, 6))
sns.scatterplot(x='size', y='cars_sold', hue='brand', palette='tab10', data=cars)
plt.xlabel('Size')
plt.ylabel('Cars Sold')
plt.title('Size vs. Cars Sold by Brand')
plt.legend(loc='upper right', bbox_to_anchor=(1.2, 1))
plt.show()
reviews_df = pd.read_csv('datasets/car_reviews.csv')
merged_df = cars.merge(reviews_df, on='model')
merged_df['review_count'].fillna(merged_df['review_count'].median(), inplace=True)
plt.figure(figsize=(14, 7))
sns.boxplot(x='brand', y='sentiment_polarity', data=merged_df)
plt.xticks(rotation=90)
plt.xlabel('Brand')
plt.ylabel('Sentiment Polarity')
plt.title('Sentiment Polarity by Brand')
plt.show()
plt.figure(figsize=(12, 6))
sns.scatterplot(x='price', y='sentiment_polarity', hue='type', palette='deep', data=merged_df)
plt.xlabel('Price')
plt.ylabel('Sentiment Polarity')
plt.title('Price vs. Sentiment Polarity by Car Type')
plt.legend(loc='upper right', bbox_to_anchor=(1.2, 1))
plt.show()
